server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:4200"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
      routes:
        - id: products-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/products/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
            - DedupeResponseHeader=Access-Control-Allow-Credentials, RETAIN_UNIQUE

        - id: category-service
          uri: http://localhost:8003
          predicates:
            - Path=/api/categoria/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
            - DedupeResponseHeader=Access-Control-Allow-Credentials, RETAIN_UNIQUE

management:
  endpoints:
    web:
      exposure:
        include: "*"